name: CWBD_E
on:
  push:
    branches: [ main ]
    paths:
    - "exp_e/**"
    
    schedule:
    - cron: "0 15 * * 1-5"
  pull_request:
    branches: [main, satish-dev]
    paths:
    - "exp_e/**"
jobs:
  container-cwbd-job-E:
    runs-on: ubuntu-latest
    
    container:
      image: python:latest
      options: --user root
      
      env:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3 

      - name: Check work folder
        run: pwd

      - name: run LS
        run: ls -lrt

      - name: run CWBD
        run: python ./exp_e/code/app.py && python ./exp_e/code/empDetails.py
      
      - name: run CWBI
        run: python ./exp_e/code/slp.py

      - name: check docker
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
