name: 'Checkout mono repository'
on:
  push:
    branches: [main, satish-dev]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Sparese Checkout
        uses: snow-actions/sparse-checkout@v1.2.0
        with:
          patterns: |
            exp_e
      
      -name: PWD
        run: pwd
      -name: Tree
        run: tree